name: terraform

on:
  pull_request:
    paths:
      - "**.tf"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.5"
      - name: fmt
        run: terraform fmt -check -recursive -diff
